### ISSUE TITLE
Error about running "train.py"

### ISSUE THREAD

**Issue by slcheng97** [jhultman/PV-RCNN#17]
I tried to run 'train.py' to train with KITTI dataset but encountered the following issue:
```
Setting up a new session...
Loading cached annotations: ../data/cache/train.pkl
Found cached database: ../data/cache/database.pkl
Epoch 0:   0%|                                          | 0/928 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/csl_project/PV-RCNN/pvrcnn/train.py", line 105, in <module>
    main()
  File "/root/csl_project/PV-RCNN/pvrcnn/train.py", line 94, in main
    scheduler, loss_fn, cfg.TRAIN.EPOCHS, start_epoch)
  File "/root/csl_project/PV-RCNN/pvrcnn/train.py", line 63, in train_model
    out = model(item)
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/csl_project/PV-RCNN/pvrcnn/detector/second.py", line 27, in forward
    features = self.feature_extract(item)
  File "/root/csl_project/PV-RCNN/pvrcnn/detector/second.py", line 22, in feature_extract
    features = self.cnn(features, item['coordinates'], item['batch_size'])
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/csl_project/PV-RCNN/pvrcnn/detector/second.py", line 45, in forward
    x = self.blocks(x)
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/spconv/modules.py", line 123, in forward
    input = module(input)
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/spconv/modules.py", line 123, in forward
    input = module(input)
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/spconv/modules.py", line 123, in forward
    input = module(input)
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/spconv/conv.py", line 161, in forward
    outids.shape[0])
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/spconv/functional.py", line 83, in forward
    return ops.indice_conv(features, filters, indice_pairs, indice_pair_num, num_activate_out, False, True)
  File "/usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/spconv/ops.py", line 112, in indice_conv
    int(inverse), int(subm))
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)` (createCublasHandle at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/cuda/CublasHandlePool.cpp:8)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7ff3eafa5627 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x4173335 (0x7ff3f0e43335 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: at::cuda::getCurrentCUDABlasHandle() + 0x458 (0x7ff3f0e43c18 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x416b092 (0x7ff3f0e3b092 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #4: THCudaBlas_Sgemm + 0x7e (0x7ff3f1248a3e in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x45c9cfb (0x7ff3f1299cfb in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: THCudaTensor_addmm + 0x57 (0x7ff3f129e607 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: <unknown function> + 0x4258914 (0x7ff3f0f28914 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x41c5fa2 (0x7ff3f0e95fa2 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #9: <unknown function> + 0x159f45d (0x7ff3ee26f45d in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #10: <unknown function> + 0x38e7265 (0x7ff3f05b7265 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #11: <unknown function> + 0x1f543 (0x7ff3cfd2d543 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/spconv/libspconv.so)
frame #12: at::Tensor spconv::indiceConv<float>(at::Tensor, at::Tensor, at::Tensor, at::Tensor, long, long, long) + 0x9f3 (0x7ff3cfd460f3 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/spconv/libspconv.so)
frame #13: c10::guts::infer_function_traits_t::return_type c10::detail::call_functor_with_args_from_stack_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor, at::Tensor, at::Tensor, at::Tensor, long, long, long), at::Tensor, c10::guts::typelist::typelist<at::Tensor, at::Tensor, at::Tensor, at::Tensor, long, long, long> >, true, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>(c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor, at::Tensor, at::Tensor, at::Tensor, long, long, long), at::Tensor, c10::guts::typelist::typelist<at::Tensor, at::Tensor, at::Tensor, at::Tensor, long, long, long> >*, std::vector<c10::IValue, std::allocator<c10::IValue> >*, std::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>) + 0x161 (0x7ff3cfd4d791 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/spconv/libspconv.so)
frame #14: c10::detail::wrap_kernel_functor_boxed<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor, at::Tensor, at::Tensor, at::Tensor, long, long, long), at::Tensor, c10::guts::typelist::typelist<at::Tensor, at::Tensor, at::Tensor, at::Tensor, long, long, long> >, true, void>::call(c10::OperatorKernel*, std::vector<c10::IValue, std::allocator<c10::IValue> >*) + 0x44 (0x7ff3cfd56864 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/spconv/libspconv.so)
frame #15: <unknown function> + 0x2fa9fc9 (0x7ff3efc79fc9 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #16: <unknown function> + 0x3ca7507 (0x7ff3f0977507 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #17: <unknown function> + 0x6ea9a7 (0x7ff41d0289a7 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #18: <unknown function> + 0x6b4fe4 (0x7ff41cff2fe4 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #19: <unknown function> + 0x28ba06 (0x7ff41cbc9a06 in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #20: _PyMethodDef_RawFastCallKeywords + 0x264 (0x559f7471fab4 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #21: _PyCFunction_FastCallKeywords + 0x21 (0x559f7471fbd1 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #22: _PyEval_EvalFrameDefault + 0x4ecb (0x559f7478657b in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #23: _PyEval_EvalCodeWithName + 0x2f9 (0x559f746cb389 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #24: _PyFunction_FastCallKeywords + 0x325 (0x559f7471f255 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #25: _PyEval_EvalFrameDefault + 0x4b39 (0x559f747861e9 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #26: _PyFunction_FastCallDict + 0x10b (0x559f746cc3fb in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #27: THPFunction_apply(_object*, _object*) + 0xa0f (0x7ff41cfb4a3f in /usr/local/miniconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #28: _PyMethodDef_RawFastCallKeywords + 0x1e0 (0x559f7471fa30 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #29: _PyCFunction_FastCallKeywords + 0x21 (0x559f7471fbd1 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #30: _PyEval_EvalFrameDefault + 0x4ecb (0x559f7478657b in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #31: _PyFunction_FastCallDict + 0x10b (0x559f746cc3fb in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #32: _PyObject_Call_Prepend + 0x63 (0x559f746eba73 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #33: PyObject_Call + 0x6e (0x559f746ddfde in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #34: _PyEval_EvalFrameDefault + 0x1e9d (0x559f7478354d in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #35: _PyEval_EvalCodeWithName + 0x2f9 (0x559f746cb389 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #36: _PyFunction_FastCallDict + 0x1d5 (0x559f746cc4c5 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #37: _PyObject_Call_Prepend + 0x63 (0x559f746eba73 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #38: <unknown function> + 0x17d27a (0x559f7473327a in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #39: _PyObject_FastCallKeywords + 0x48b (0x559f747342db in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #40: _PyEval_EvalFrameDefault + 0x4a96 (0x559f74786146 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #41: _PyFunction_FastCallDict + 0x10b (0x559f746cc3fb in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #42: _PyObject_Call_Prepend + 0x63 (0x559f746eba73 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #43: PyObject_Call + 0x6e (0x559f746ddfde in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #44: _PyEval_EvalFrameDefault + 0x1e9d (0x559f7478354d in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #45: _PyEval_EvalCodeWithName + 0x2f9 (0x559f746cb389 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #46: _PyFunction_FastCallDict + 0x1d5 (0x559f746cc4c5 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #47: _PyObject_Call_Prepend + 0x63 (0x559f746eba73 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #48: <unknown function> + 0x17d27a (0x559f7473327a in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #49: _PyObject_FastCallKeywords + 0x48b (0x559f747342db in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #50: _PyEval_EvalFrameDefault + 0x4a96 (0x559f74786146 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #51: _PyFunction_FastCallDict + 0x10b (0x559f746cc3fb in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #52: _PyObject_Call_Prepend + 0x63 (0x559f746eba73 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #53: PyObject_Call + 0x6e (0x559f746ddfde in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #54: _PyEval_EvalFrameDefault + 0x1e9d (0x559f7478354d in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #55: _PyEval_EvalCodeWithName + 0x2f9 (0x559f746cb389 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #56: _PyFunction_FastCallDict + 0x1d5 (0x559f746cc4c5 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #57: _PyObject_Call_Prepend + 0x63 (0x559f746eba73 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #58: <unknown function> + 0x17d27a (0x559f7473327a in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #59: _PyObject_FastCallKeywords + 0x48b (0x559f747342db in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #60: _PyEval_EvalFrameDefault + 0x4a96 (0x559f74786146 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #61: _PyFunction_FastCallDict + 0x10b (0x559f746cc3fb in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #62: _PyObject_Call_Prepend + 0x63 (0x559f746eba73 in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)
frame #63: PyObject_Call + 0x6e (0x559f746ddfde in /usr/local/miniconda3/envs/pvrcnn/bin/python3.7m)

Epoch 0:   0%|                                          | 0/928 [01:07<?, ?it/s]

Process finished with exit code 1
```
I don't know how to solve this problem, could you help me?

**Comment by jhultman** [comment]
Hi, thanks for your question. Can you try reducing batch size? Sometimes out of memory gives cryptic error message.

**Comment by jhultman** [comment]
Closing due to inactivity.
